image: "python:3.7"

services:
  - mongo:latest

variables:
  # Python
  PYTHON_END: "DEVELOPMENT"

  # Mongo
  MONGO_URL: 'mongodb://mongo:27017'

before_script:
  - python3 -m pip install -r requirements.txt

stages:
  - Test

unittest:
  stage: Test
  script:
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - python -m unittest discover -s test -p "*_test.py"
